# Docker Compose オーバーライドファイル
# .env ファイルと組み合わせて環境変数を使用した設定を可能にします
# 使用方法: .env ファイルを作成して環境変数を設定してから docker-compose up

services:
  koalawiki:
    environment:
      - KOALAWIKI_REPOSITORIES=${KOALAWIKI_REPOSITORIES}
      - TASK_MAX_SIZE_PER_USER=${TASK_MAX_SIZE_PER_USER}
      - REPAIR_MERMAID=${REPAIR_MERMAID}
      - CHAT_MODEL=${CHAT_MODEL}
      - ANALYSIS_MODEL=${ANALYSIS_MODEL}
      - CHAT_API_KEY=${CHAT_API_KEY}
      - LANGUAGE=${LANGUAGE}
      - ENDPOINT=${ENDPOINT}
      - MODEL_PROVIDER=${MODEL_PROVIDER}
      # Amazon Bedrock 環境変数
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DB_TYPE=${DB_TYPE}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL}
      - EnableSmartFilter=${EnableSmartFilter}
      - ENABLE_INCREMENTAL_UPDATE=${ENABLE_INCREMENTAL_UPDATE}
      - ENABLE_CODED_DEPENDENCY_ANALYSIS=${ENABLE_CODED_DEPENDENCY_ANALYSIS}
      - ENABLE_WAREHOUSE_FUNCTION_PROMPT_TASK=${ENABLE_WAREHOUSE_FUNCTION_PROMPT_TASK}
      - ENABLE_WAREHOUSE_DESCRIPTION_TASK=${ENABLE_WAREHOUSE_DESCRIPTION_TASK}